version: '3'
services:
  nginx:
    ports:
      - '80:80'

  auth-jwt:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./.env.production
    command: npm run start:jwt
