version: '3'
services:
  auth-jwt:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
