version: '3'
services:
  nginx:
    ports:
      - '3000:80'

  auth-jwt:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env.development
    command: npm run dev:jwt
